### ISSUE TITLE
IndexIDMap2 has no 'at' attribute anymore in versions 1.5.3 and above

### ISSUE THREAD

**Issue by lstefanou** [facebookresearch/faiss#1020]
# Summary

Up until version 1.5.2, I am able to retrieve the IDs from a IndexIDMap2 object with the following code: 

`[index.id_map.at(int(i)) for i in range(index.ntotal)]`

With version 1.5.3 and up, this behaviour seems to have been removed, the following error is raised:

`[index.id_map.at(int(i)) for i in range(index.ntotal)]`
`E   AttributeError: 'SwigPyObject' object has no attribute 'at'`

Is there another way to retrieve the IDs from an IDMap with newer versions of Faiss? If not, why was this functionality removed?

# Platform

OS: MacOS 10.14.4

Faiss version: 1.6.0

Faiss compilation options: 

Running on:
- [x] CPU

Interface: 
- [x] Python

# Reproduction instructions
    n_features = 10000
    feature_dims = 40

    features = np.random.random((n_features, feature_dims)).astype(np.float32)
    idx = np.arange(n_features).astype(np.int64)

    index = faiss.IndexFlatL2(feature_dims)
    index = faiss.IndexIDMap2(index)
    index.add_with_ids(features, idx)

    [index.id_map.at(int(i)) for i in range(index.ntotal)]

The above will work fine in 1.5.2, but not in 1.5.3 and up.

**Comment by mdouze** [comment]
Probably some weird interaction between SWIG and C++ templates... 
I'll take a look.

**Comment by mdouze** [comment]
Can't repro with 1.6.0 
https://gist.github.com/mdouze/5d45379b8d1919f30483e5ec96818883

**Comment by autocyz** [comment]
The same error when faiss-cpu==1.6.1,   1.6.0 is ok

**Comment by bfelbo** [comment]
@mdouze I'm getting the exact same error when I run your gist. My platform info is below.

OS: MacOS 10.14.4
Faiss version: 1.6.3
Running on: CPU Python

**Comment by bfelbo** [comment]
Your gist runs fine on the following setup.

OS: Ubuntu 16.04.5 LTS
Faiss version: 1.6.1
Running on: CPU Python

**Comment by mdouze** [comment]
I can repro the issue on 
Weird because this is tested in 
https://github.com/facebookresearch/faiss/blob/22b7876ef5540b85feee173aa3182a2f37dc98f6/tests/test_build_blocks.py#L584
