### PR TITLE
Fix Dockerfile build and tests

### PR DESCRIPTION
**Pull request by yutkin**
Current [Dockerfile](https://github.com/facebookresearch/faiss/blob/master/Dockerfile) fails on tests building `nvidia-docker build -t faiss github.com/facebookresearch/faiss`:
```
test_shards (test_meta_index.Shards) ... ok
test_openmp (test_omp_threads_py.TestOpenMP) ... ok
test_outrageous_alloc (test_oom_exception.TestOOMException) ... ok
test_IDMap (test_referenced_objects.TestReferenced) ... ok
test_IndexIVF (test_referenced_objects.TestReferenced) ... WARNING clustering 100 points to 10 centroids: please provide at least 390 training points
ok
test_IndexIVF_2 (test_referenced_objects.TestReferenced) ... WARNING clustering 100 points to 10 centroids: please provide at least 390 training points
ok
test_IndexPreTransform (test_referenced_objects.TestReferenced) ... ok
test_IndexPreTransform_2 (test_referenced_objects.TestReferenced) ... ok
test_count_refs (test_referenced_objects.TestReferenced) ... ok
test_shards (test_referenced_objects.TestReferenced) ... ok
test_binary_ivf (test_referenced_objects.TestReferencedBinary) ... WARNING clustering 100 points to 10 centroids: please provide at least 390 training points
ok
test_wrap (test_referenced_objects.TestReferencedBinary) ... ok

======================================================================
ERROR: test_extra_distances (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_extra_distances
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/opt/faiss/tests/test_extra_distances.py", line 16, in <module>
    import scipy.spatial.distance
ImportError: No module named scipy.spatial.distance


======================================================================
ERROR: test_OIVFPQ (test_index_accuracy.OPQRelativeAccuracy)
----------------------------------------------------------------------

...

Traceback (most recent call last):
  File "/opt/faiss/tests/test_index_accuracy.py", line 522, in test_OIVFPQ
    ev = Randu10kUnbalanced()
  File "/opt/faiss/tests/common.py", line 65, in __init__
    self.xb /= np.linalg.norm(self.xb, axis=1)[:, np.newaxis]
TypeError: norm() got an unexpected keyword argument 'axis'

======================================================================
ERROR: test_OPQ (test_index_accuracy.OPQRelativeAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/faiss/tests/test_index_accuracy.py", line 493, in test_OPQ
    ev = Randu10kUnbalanced()
  File "/opt/faiss/tests/common.py", line 65, in __init__
    self.xb /= np.linalg.norm(self.xb, axis=1)[:, np.newaxis]
TypeError: norm() got an unexpected keyword argument 'axis'

----------------------------------------------------------------------
Ran 128 tests in 53.408s

FAILED (errors=3)
make: *** [test] Error 1
```

I replaced outdated Python and NumPy and fix `print` function in a test file.

### CODE REVIEW

File: Dockerfile [hunk 1]
```diff
@@ -13,17 +13,24 @@ ENV LD_PRELOAD /usr/lib64/libgomp.so.1:/opt/intel/mkl/lib/intel64/libmkl_def.so:
...
 
-# Install necesary headers/libs
-RUN yum install -y python-devel numpy
+# Install Python and necesary headers/libs
+RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm && \
+    yum -y install python36u-devel python36u-pip && \
+    ln -sf /usr/bin/python3.6 /usr/bin/python && \
+    ln -sf /usr/bin/pip3.6 /usr/bin/pip && \
+    pip install -U pip numpy==1.17.0 scipy==1.3.1 && \
+    rm -rf /root/.cache/pip
```
Comment (beauby) [inline Dockerfile]: This seems overkill. The reason for tests failing here is that `scipy` is missing, so I'd be in favor of a fix that just adds (a suitable version of) scipy.

Comment (yutkin) [reply Dockerfile]: I think upgrading to Python 3 is also a good idea because Python 2 [will retire in ~4 months](https://pythonclock.org/). Is not it?

**Comment by algoriddle** [comment]
We removed all docker-based builds in v1.7.4, closing.
