### PR TITLE
Support grouping of vector data in HNSW

### PR DESCRIPTION
**Pull request by heemin32**
Add IDGrouper in SearchParameter so that it can be used to dedupe search result based on its group id

### CODE REVIEW

**Comment by heemin32** [comment]
@mdouzz, would you mind taking a look?

**Comment by mdouze** [comment]
Sorry for being unresponsive. 
The reason I'm reluctant with this solution is that IMO the new ResultHandler API makes it possible to move the whole de-duplication logic outside of Faiss. In the calling code, just set up a `ResultHandler` class that does the deduplication and call `hnsw.search` on that.

**Comment by heemin32** [comment]
I search HNSW through IndexIDMap. Do you have a plan to expand the ResultHandler to IndexIDMap?

**Comment by mdouze** [comment]
I still have to write an example with a custom ResultHandler.

**Comment by wntmddus** [comment]
Hello, I have seen this getting patched into k-nn-opensearch-plugin on 2.15.0 version. and this used to be working well with gcc-c++ version 8.5.0-22.0.1 but when we introduced new linux image with gcc-c++ version 11.4.1-3.0.1, this caused error on ResultHandler where GroupedHeapBlockResultHandler is at.

`[100%] Linking CXX shared library release/libopensearchknn_nmslib.so
[100%] Built target opensearchknn_nmslib
[  0%] Building CXX object external/faiss/faiss/CMakeFiles/faiss.dir/AutoTune.cpp.o
[  0%] Building CXX object external/faiss/faiss/CMakeFiles/faiss.dir/Clustering.cpp.o
[  3%] Building CXX object external/faiss/faiss/CMakeFiles/faiss.dir/IVFlib.cpp.o
[  3%] Building CXX object external/faiss/faiss/CMakeFiles/faiss.dir/Index.cpp.o
[  3%] Building CXX object external/faiss/faiss/CMakeFiles/faiss.dir/Index2Layer.cpp.o
[  6%] Building CXX object external/faiss/faiss/CMakeFiles/faiss.dir/IndexAdditiveQuantizer.cpp.o
In file included from /sparta/input/jni/external/faiss/faiss/IndexAdditiveQuantizer.cpp:19:
/sparta/input/jni/external/faiss/faiss/impl/ResultHandler.h:128:58: error: expected template-name before '<' token
  128 | struct GroupedHeapBlockResultHandler : BlockResultHandler<C> {
      |                                                          ^
/sparta/input/jni/external/faiss/faiss/impl/ResultHandler.h:128:58: error: expected '{' before '<' token
make[3]: *** [external/faiss/faiss/CMakeFiles/faiss.dir/build.make:146: external/faiss/faiss/CMakeFiles/faiss.dir/IndexAdditiveQuantizer.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:549: external/faiss/faiss/CMakeFiles/faiss.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:348: CMakeFiles/opensearchknn_faiss.dir/rule] Error 2
make: *** [Makefile:228: opensearchknn_faiss] Error 2
> Task :buildJniLib FAILED`

@heemin32
