### ISSUE TITLE
Problems with SIMD when compiling for ARM (Apple M1)

### ISSUE THREAD

**Issue by vsolovyov** [facebookresearch/faiss#1880]
When I try to compile Faiss, it complains in this way:

```
In file included from /Users/murkt/dev/faiss/faiss/impl/pq4_fast_scan_search_1.cpp:11:
In file included from /Users/murkt/dev/faiss/faiss/impl/simd_result_handlers.h:15:
In file included from /Users/murkt/dev/faiss/faiss/utils/simdlib.h:23:
/Users/murkt/dev/faiss/faiss/utils/simdlib_neon.h:256:54: error: argument to '__builtin_neon_vshrq_n_v' must be a constant integer
                data, [shift](uint16x8_t a) { return vshrq_n_u16(a, shift); })};
                                                     ^              ~~~~~
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include/arm_neon.h:25132:24: note: expanded from macro 'vshrq_n_u16'
  __ret = (uint16x8_t) __builtin_neon_vshrq_n_v((int8x16_t)__s0, __p1, 49); \
                       ^                                         ~~~~
```

There are a bunch of them, each time `simdlib_neon.h` is included.

# Platform

OS: macOS 11.3
Faiss version: b4c320a671e58252b229f12459f2d9c285e8b535
Clang: 12.0.5
SWIG: 4.0.2b
cmake: 3.20.1

Compiling Faiss with these:

```
cmake -B build -DBUILD_TESTING=ON -DFAISS_ENABLE_GPU=OFF -DCMAKE_BUILD_TYPE=Release -DFAISS_ENABLE_C_API=ON -DPython_EXECUTABLE=`which python3`
make -C build -j faiss
```

Code in `faiss/utils/simdlib_neon.h` seems to already be aware of the issue that `shift` argument must be a constant integer:

```
    // shift must be known at compile time
    simd16uint16 operator>>(const int shift) const {
        return simd16uint16{detail::simdlib::unary_func(
                data, [shift](uint16x8_t a) { return vshrq_n_u16(a, shift); })};
    }

    // shift must be known at compile time
    simd16uint16 operator<<(const int shift) const {
        return simd16uint16{detail::simdlib::unary_func(
                data, [shift](uint16x8_t a) { return vshlq_n_u16(a, shift); })};
    }
```

I'm not a C++ expert. As I understand, we have a lambda here, and for some reason it doesn't capture that `shift` is `const` indeed and is known at compile time. I searched around and found that maybe `std::as_const` can help here (was added in C++17).

I tried to change `[shift]` to `[shift = std::as_const(shift)]` and change C++ version in CMakeLists.txt with `set(CMAKE_CXX_STANDARD 17)`, but it doesn't work too.

Faiss 1.7.0 compiles, because there is no `faiss/utils/simdlib_neon.h`, but when I try to compile tests with `make -C build -j faiss_test` it fails with:

```
[100%] Linking CXX executable faiss_test
Undefined symbols for architecture arm64:
  "faiss::fvec_inner_products_ny(float*, float const*, float const*, unsigned long, unsigned long)", referenced from:
      faiss::ProductQuantizer::compute_inner_prod_table(float const*, float*) const in libfaiss.a(ProductQuantizer.cpp.o)
      _.omp_outlined..5 in libfaiss.a(ProductQuantizer.cpp.o)
ld: symbol(s) not found for architecture arm64
```

I also tried to compile version 27077c46274f87a50a0a28fb90433d6cfc029741 where #1655 was merged. It compiles and 100% tests pass.

**Comment by vsolovyov** [comment]
`simdlib_neon.h` was introduced in https://github.com/facebookresearch/faiss/pull/1815, maybe @vorj can help with the issue?

**Comment by vorj** [comment]
> I tried to change `[shift]` to `[shift = std::as_const(shift)]` and change C++ version in CMakeLists.txt with `set(CMAKE_CXX_STANDARD 17)`, but it doesn't work too.

In this context, _constant integer_ means **compiletime** constant, so `std::as_const` doesn't help us.

The problem comes from the difference in the implementations of intrinsics on GCC and Clang.
`__builtin_aarch64_lshrv8hi` , which is builtin function of implementation for `vshrq_n_u16` on GCC, accepts runtime integer, but `__builtin_neon_vshrq_n_v` , which is builtin function of implementation for `vshrq_n_u16` on Clang, declines runtime integer.
We can write workaround for this issue, so please wait a minute.

**Comment by LWisteria** [comment]
[Neon Intrinsics Reference](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics?search=vshrq_n_u16) says `vshrq_n_u16` is `Unsigned Shift Right (immediate)`.

`immediate` means compiletime constant, thus, Clang is right.

**Comment by mdouze** [comment]
Please follow discussion in the PR.

**Comment by h-vetinari** [comment]
@vorj @LWisteria 
Has someone raised a bug against GCC for this?

**Comment by LWisteria** [comment]
@h-vetinari I don't think it's a compiler bug, but just a kind of "unspecified behavior":

* The ARM reference says nothing about what should be happened if you input non-immediate (non-compile-time constant) variables. It guarantees only that immediate variables must be supported at least.
* Immediate variables are already acceptable by Clang and also by GCC. Clang chose to omit an error for non-immediate, and GCC to accept.
* Therefore, we, ARM SIMD programmers, should follow the reference strictly and use only immediate variables to keep code's portability.

The GCC developers could welcome you to send a feature request and/or request to modify its behavior to omit an error. But it looks not necessary for me.

@vorj How do you think?

**Comment by vorj** [comment]
That behavior of GCC has made me careless, but I agree @LWisteria 's opinion.
